//SolidEdgeDraft 常用函数
namespace SolidEdgeDraft{
	getTitleBlock=function(seSht){
        for (i = 1;  seSht.BlockOccurrences.Count ) { //获取Titleblock
            select  (seSht.BlockOccurrences.Item(i).Block.Name){
                case "Title 2020", "Title", "Title-SRDC_V1", "Title-SRDC" {
                    seBlk = seSht.BlockOccurrences.Item(i)
                    return seBlk ;
                }
            }
        }
	}
	getLabelTable=function(blk){
		var seLbs=blk.BlockLabelOccurrences		
		var tar={}
		for (i=1;seLbs.count){
    		tar[seLbs.item(i).name]=..string.trim(seLbs.item(i).value)
    		tar["零件名称"] := tar["名称(中文)"] 
		}		
		return tar; 
	}
	getValueFromBlk=function(blk, lableName){
		var seLbs=blk.BlockLabelOccurrences		
		for (i=1;seLbs.count){
    		if (seLbs.item(i).name==lableName) return seLbs.item(i).value
		}
	}
	getVerFromShtCorner=function(seSht){
        txts = seSht.TextBoxes        
        for (i = 1 ; txts.Count){
            var x,y,z=txts.Item(i).GetOrigin( )
            //Debug.Print txts.Item(i).Text, x * 1000, y * 1000, z * 1000
            if (..string.len(..string.trim(txts.Item(i).Text)) == 2) {
                if (x * 1000 > 395 && y * 1000 > 10) {
                    return ..string.trim(txts.Item(i).Text)
                }
            }
        }
	}
	getVerFromBlkCorner=function(blk){
        txts = blk.Block.Views.Item(1).TextBoxes
        txtbox = txts.Item(1)
        if (txts && txtbox) {
            var a,b,c=txtbox.GetOrigin ( )
            for (i = 2 ; txts.Count){
                var x,y,z=txts.Item(i).GetOrigin ()
                if (x > a || y < b) {
                    txtbox = txts.Item(i)
                    a,b,c=txtbox.GetOrigin ()
                }
            }
        }
        return ..string.trim(txtbox.Text)
	}
		
}
/**intellisense(VBASettingIO)
getTitleBlock(sht) = @1 图纸工作表\r\n 返回值: block实例
getLabelTable(blk)  = @1 block实例 \r\n 返回值: lable array
end intellisense**/